### ISSUE TITLE
KST x06

### ISSUE THREAD

**Issue by ExplodedView-Studios** [guillaumef/wing-servo-frame#1]
KST x06 Please.
Case Dimensions: 20mm x 7mm x 16.6mm ±0.2mm.
![kst-x06-servo-1-8kg-cm-0-07s-6-4g-7mm-110-540w](https://user-images.githubusercontent.com/52623560/127811758-6802a4fc-bca7-4e1e-b745-dce288360c3e.jpg)

**Comment by guillaumef** [comment]
Integrated in last commit

**Comment by ExplodedView-Studios** [comment]
Thank You
Much Appreciated
