### ISSUE TITLE
MKS HV6110 wing servo frame

### ISSUE THREAD

**Issue by cozzierich** [guillaumef/wing-servo-frame#2]
I see you have servo frames for the MKS-6100 and was wondering if you could add servo frames for the MKS-HV6110.

Thank you.

**Comment by guillaumef** [comment]
Hi,

DS6100 and HV6100 have the same dimensions. 
http://www.mks-servo.com/image/Glider%20Servo/Dimension/DS6100_Dimension01.jpg
http://www.mks-servo.com/image/Glider%20Servo/Dimension/HV6100_Dimension.jpg

It was specified in the servo-frame.scad and the homepage here.
/* Servo #0,0    - MKS DS6100 / HV6100                                           */
MKS DS6100 / HV6100

So you can use the DS6100 stls directly.

Enjoy! Put a star the project and talk about it ;-)
Thank you!
